version: '3'
services:
  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: node index.js
    expose:
      - "3000"
    networks:
      - app-net

  api:
    image: node:18
    working_dir: /app
    volumes:
      - ./api:/app
    command: node index.js
    expose:
      - "3001"
    networks:
      - app-net

  admin:
    image: node:18
    working_dir: /app
    volumes:
      - ./admin:/app
    command: node index.js
    expose:
      - "3002"
    networks:
      - app-net

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - api
      - admin
    networks:
      - app-net

networks:
  app-net:
