version: '3'
services:
  web:
    build: .
    expose:
      - "3000"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - app-network

networks:
  app-network:
