version: '3'
services:
  web:
    build: .
    expose:
      - "3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/testdb
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:6
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
